//! UPDATE confirmation modal — center overlay that shows the SQL the
//! tool is about to run and prompts y/n. Owned by `App::confirm_update`.
//!
//! The SQL is generated by `sql_format::format_update_one` based on
//! the cell's source `RelationRef`, the row's PK value, and the new
//! value parsed by the cell-edit modal. Caller dispatches the SQL on
//! confirm.

use ratatui::layout::Rect;
use ratatui::style::{Color, Modifier, Style};
use ratatui::text::{Line, Span};
use ratatui::widgets::{Block, Borders, Clear, Paragraph};
use ratatui::Frame;

use crate::types::CellValue;

#[derive(Debug)]
pub struct ConfirmUpdateState {
    /// The full SQL statement, identifier-quoted and value-escaped.
    /// Shown verbatim in the modal — nothing extra is sent to the
    /// server.
    pub sql: String,
    /// Coords of the cell the user is updating, so on success the
    /// app can patch it in place in the result set.
    pub row: usize,
    pub col: usize,
    /// New value, ready to drop into `ResultSet.rows[row][col]` after
    /// the server confirms the UPDATE succeeded.
    pub new_value: CellValue,
}

pub fn draw(frame: &mut Frame<'_>, state: &ConfirmUpdateState, screen: Rect) {
    let lines: Vec<&str> = state.sql.split('\n').collect();
    let body_height = (lines.len() as u16).max(1);
    let height = (body_height + 4).min(screen.height); // +4 = borders + prompt line
    let width = ((state
        .sql
        .lines()
        .map(|l| l.chars().count() as u16)
        .max()
        .unwrap_or(40))
        + 4)
    .max(50)
    .min(screen.width);
    let area = Rect {
        x: screen.x + (screen.width.saturating_sub(width)) / 2,
        y: screen.y + (screen.height.saturating_sub(height)) / 2,
        width,
        height,
    };

    let mut text: Vec<Line> = lines
        .iter()
        .map(|l| {
            Line::from(Span::styled(
                l.to_string(),
                Style::default()
                    .fg(Color::White)
                    .add_modifier(Modifier::BOLD),
            ))
        })
        .collect();
    text.push(Line::from(""));
    text.push(Line::from(Span::styled(
        "Execute? (y)es / (n)o",
        Style::default()
            .fg(Color::Yellow)
            .add_modifier(Modifier::BOLD),
    )));

    let block = Block::default()
        .borders(Borders::ALL)
        .title(" Confirm UPDATE ")
        .border_style(Style::default().fg(Color::Yellow));
    let p = Paragraph::new(text).block(block);
    frame.render_widget(Clear, area);
    frame.render_widget(p, area);
}
